name: Build Auritia

on: [pull_request]

jobs:
  build-linux:
    name: "🐧 Compile for Linux"
    runs-on: ubuntu-latest
    steps: 

    - name: 🧪 Environment Info
      run: "npx envinfo"

    - name: 🛎 Checkout
      uses: actions/checkout@v2

    - name: ⚡ Install NPM Dependancies
      run: "npm i"

    - name: 🛠 Build 
      run: npm run compile

    - name: 🗳 Upload artifact 
      uses: actions/upload-artifact@v1
      with:
        name: auritia_compiled_linux_${{matrix.targetPlatform}}
        path: src-tauri/target/release/auritia